### PR TITLE
testing

### PR DESCRIPTION
**Pull request by bhima2001**

### CODE REVIEW

**Comment by bhima2001** [comment]
Hey, I am sorry. I won't be able to work on this.

**Comment by bhima2001** [comment]
Hey, sorry for the delay. It took me sometime to understand and make husky work locally. I have a doubt should husky be applied to only the app/web folder or for the entire project. Again thanks for being patient

**Comment by BirushaNdegeya** [comment]
### Hey @bhima2001  👋👋

Husky should be applied to the entire project, covering both the **app/web** and **app/api** folders. 
This way, you ensure that all changes are validated before commits, maintaining code quality across the board. 

Thanks for bringing this up && Happy coding...🚛🚛✈️

**Comment by bhima2001** [comment]
Also I have one more question, Should I use the same version of eslint, which is present in the app/web folder or go for the latest version. I am thinking to setup a barebone structure and link husky i.e. pre-commit with eslint along with lint-staged to only check the lint on staged files and pre-push

**Comment by BirushaNdegeya** [comment]
Yes, you can update eslint and pick up the latest version.

**Pull request closed without merging**
